"""create_observability_models

Revision ID: 20260718_0009
Revises: 20260718_0008
Create Date: 2026-07-18 13:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260718_0009'
down_revision: Union[str, None] = '20260718_0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observability_integrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('auth_method', sa.String(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_integrations_integration_type'), 'observability_integrations', ['integration_type'], unique=False)
    op.create_index(op.f('ix_observability_integrations_name'), 'observability_integrations', ['name'], unique=False)
    op.create_index(op.f('ix_observability_integrations_project_id'), 'observability_integrations', ['project_id'], unique=False)
    op.create_index(op.f('ix_observability_integrations_workspace_id'), 'observability_integrations', ['workspace_id'], unique=False)

    op.create_table('alertmanager_silences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('silence_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('matchers', sa.JSON(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['observability_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertmanager_silences_integration_id'), 'alertmanager_silences', ['integration_id'], unique=False)
    op.create_index(op.f('ix_alertmanager_silences_silence_id'), 'alertmanager_silences', ['silence_id'], unique=False)
    op.create_index(op.f('ix_alertmanager_silences_status'), 'alertmanager_silences', ['status'], unique=False)

    op.create_table('grafana_dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('folder_title', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('panels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['observability_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grafana_dashboards_integration_id'), 'grafana_dashboards', ['integration_id'], unique=False)
    op.create_index(op.f('ix_grafana_dashboards_title'), 'grafana_dashboards', ['title'], unique=False)
    op.create_index(op.f('ix_grafana_dashboards_uid'), 'grafana_dashboards', ['uid'], unique=False)

    op.create_table('prometheus_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('annotations', sa.JSON(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['observability_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prometheus_rules_group_name'), 'prometheus_rules', ['group_name'], unique=False)
    op.create_index(op.f('ix_prometheus_rules_integration_id'), 'prometheus_rules', ['integration_id'], unique=False)
    op.create_index(op.f('ix_prometheus_rules_name'), 'prometheus_rules', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prometheus_rules')
    op.drop_table('grafana_dashboards')
    op.drop_table('alertmanager_silences')
    op.drop_table('observability_integrations')
    # ### end Alembic commands ###
