"""create_trace_models

Revision ID: 20260718_0006
Revises: 20260718_0005
Create Date: 2026-07-18 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260718_0006'
down_revision: Union[str, None] = '20260718_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('root_span_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_project_id'), 'traces', ['project_id'], unique=False)
    op.create_index(op.f('ix_traces_workspace_id'), 'traces', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_traces_root_span_id'), 'traces', ['root_span_id'], unique=False)
    op.create_index(op.f('ix_traces_start_time'), 'traces', ['start_time'], unique=False)
    op.create_index(op.f('ix_traces_trace_id'), 'traces', ['trace_id'], unique=True)

    op.create_table('spans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('span_id', sa.String(), nullable=False),
    sa.Column('parent_span_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('span_attributes', sa.JSON(), nullable=False),
    sa.Column('resource_attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_name'), 'spans', ['name'], unique=False)
    op.create_index(op.f('ix_spans_parent_span_id'), 'spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_spans_project_id'), 'spans', ['project_id'], unique=False)
    op.create_index(op.f('ix_spans_span_id'), 'spans', ['span_id'], unique=True)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)

    op.create_table('span_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['span_id'], ['spans.span_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_span_events_span_id'), 'span_events', ['span_id'], unique=False)

    op.create_table('span_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.String(), nullable=False),
    sa.Column('linked_trace_id', sa.String(), nullable=False),
    sa.Column('linked_span_id', sa.String(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['span_id'], ['spans.span_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_span_links_linked_span_id'), 'span_links', ['linked_span_id'], unique=False)
    op.create_index(op.f('ix_span_links_linked_trace_id'), 'span_links', ['linked_trace_id'], unique=False)
    op.create_index(op.f('ix_span_links_span_id'), 'span_links', ['span_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_span_links_span_id'), table_name='span_links')
    op.drop_index(op.f('ix_span_links_linked_trace_id'), table_name='span_links')
    op.drop_index(op.f('ix_span_links_linked_span_id'), table_name='span_links')
    op.drop_table('span_links')
    op.drop_index(op.f('ix_span_events_span_id'), table_name='span_events')
    op.drop_table('span_events')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_project_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_name'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_traces_trace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_start_time'), table_name='traces')
    op.drop_index(op.f('ix_traces_root_span_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_workspace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_project_id'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
