"""create_k8s_models

Revision ID: 20260718_0008
Revises: 20260718_0007
Create Date: 2026-07-18 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260718_0008'
down_revision: Union[str, None] = '20260718_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8s_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('kubernetes_version', sa.String(), nullable=True),
    sa.Column('auth_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_clusters_name'), 'k8s_clusters', ['name'], unique=False)
    op.create_index(op.f('ix_k8s_clusters_project_id'), 'k8s_clusters', ['project_id'], unique=False)
    op.create_index(op.f('ix_k8s_clusters_workspace_id'), 'k8s_clusters', ['workspace_id'], unique=False)

    op.create_table('k8s_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('available_replicas', sa.Integer(), nullable=False),
    sa.Column('ready_replicas', sa.Integer(), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_deployments_cluster_id'), 'k8s_deployments', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_k8s_deployments_name'), 'k8s_deployments', ['name'], unique=False)
    op.create_index(op.f('ix_k8s_deployments_namespace'), 'k8s_deployments', ['namespace'], unique=False)

    op.create_table('k8s_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('involved_object_kind', sa.String(), nullable=False),
    sa.Column('involved_object_name', sa.String(), nullable=False),
    sa.Column('first_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_events_cluster_id'), 'k8s_events', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_k8s_events_involved_object_kind'), 'k8s_events', ['involved_object_kind'], unique=False)
    op.create_index(op.f('ix_k8s_events_involved_object_name'), 'k8s_events', ['involved_object_name'], unique=False)
    op.create_index(op.f('ix_k8s_events_last_timestamp'), 'k8s_events', ['last_timestamp'], unique=False)
    op.create_index(op.f('ix_k8s_events_namespace'), 'k8s_events', ['namespace'], unique=False)
    op.create_index(op.f('ix_k8s_events_reason'), 'k8s_events', ['reason'], unique=False)

    op.create_table('k8s_namespaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_namespaces_cluster_id'), 'k8s_namespaces', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_k8s_namespaces_name'), 'k8s_namespaces', ['name'], unique=False)

    op.create_table('k8s_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('os_image', sa.String(), nullable=True),
    sa.Column('kernel_version', sa.String(), nullable=True),
    sa.Column('container_runtime_version', sa.String(), nullable=True),
    sa.Column('cpu_capacity', sa.String(), nullable=True),
    sa.Column('memory_capacity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_nodes_cluster_id'), 'k8s_nodes', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_k8s_nodes_name'), 'k8s_nodes', ['name'], unique=False)

    op.create_table('k8s_pods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('pod_ip', sa.String(), nullable=True),
    sa.Column('host_ip', sa.String(), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_pods_cluster_id'), 'k8s_pods', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_k8s_pods_name'), 'k8s_pods', ['name'], unique=False)
    op.create_index(op.f('ix_k8s_pods_namespace'), 'k8s_pods', ['namespace'], unique=False)
    op.create_index(op.f('ix_k8s_pods_node_name'), 'k8s_pods', ['node_name'], unique=False)
    op.create_index(op.f('ix_k8s_pods_phase'), 'k8s_pods', ['phase'], unique=False)

    op.create_table('k8s_containers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('state_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['k8s_pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_containers_name'), 'k8s_containers', ['name'], unique=False)
    op.create_index(op.f('ix_k8s_containers_pod_id'), 'k8s_containers', ['pod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k8s_containers')
    op.drop_table('k8s_pods')
    op.drop_table('k8s_nodes')
    op.drop_table('k8s_namespaces')
    op.drop_table('k8s_events')
    op.drop_table('k8s_deployments')
    op.drop_table('k8s_clusters')
    # ### end Alembic commands ###
