"""create_remediation_models

Revision ID: 20260718_0010
Revises: 20260718_0009
Create Date: 2026-07-18 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260718_0010'
down_revision: Union[str, None] = '20260718_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('remediation_type', sa.String(), nullable=False),
    sa.Column('patch_content', sa.String(), nullable=True),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('potential_risks', sa.JSON(), nullable=False),
    sa.Column('expected_impact', sa.String(), nullable=False),
    sa.Column('rollback_plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_plans_incident_id'), 'remediation_plans', ['incident_id'], unique=False)
    op.create_index(op.f('ix_remediation_plans_remediation_type'), 'remediation_plans', ['remediation_type'], unique=False)
    op.create_index(op.f('ix_remediation_plans_status'), 'remediation_plans', ['status'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remediation_plan_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_remediation_plan_id'), 'approval_requests', ['remediation_plan_id'], unique=False)

    op.create_table('draft_pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remediation_plan_id', sa.Uuid(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_url', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('base_sha', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_pull_requests_remediation_plan_id'), 'draft_pull_requests', ['remediation_plan_id'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remediation_plan_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output_log', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_remediation_plan_id'), 'validation_results', ['remediation_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_table('draft_pull_requests')
    op.drop_table('approval_requests')
    op.drop_table('remediation_plans')
    # ### end Alembic commands ###
