"""create_github_models

Revision ID: 20260718_0007
Revises: 20260718_0006
Create Date: 2026-07-18 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260718_0007'
down_revision: Union[str, None] = '20260718_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('github_repo_id', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repositories_full_name'), 'github_repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_github_repositories_github_repo_id'), 'github_repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_github_repositories_name'), 'github_repositories', ['name'], unique=False)
    op.create_index(op.f('ix_github_repositories_owner'), 'github_repositories', ['owner'], unique=False)
    op.create_index(op.f('ix_github_repositories_project_id'), 'github_repositories', ['project_id'], unique=False)
    op.create_index(op.f('ix_github_repositories_workspace_id'), 'github_repositories', ['workspace_id'], unique=False)

    op.create_table('github_commits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('parents', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_commits_repository_id'), 'github_commits', ['repository_id'], unique=False)
    op.create_index(op.f('ix_github_commits_sha'), 'github_commits', ['sha'], unique=True)
    op.create_index(op.f('ix_github_commits_timestamp'), 'github_commits', ['timestamp'], unique=False)

    op.create_table('github_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_deployments_commit_sha'), 'github_deployments', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_github_deployments_deployment_id'), 'github_deployments', ['deployment_id'], unique=True)
    op.create_index(op.f('ix_github_deployments_deployed_at'), 'github_deployments', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_github_deployments_environment'), 'github_deployments', ['environment'], unique=False)
    op.create_index(op.f('ix_github_deployments_project_id'), 'github_deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_github_deployments_repository_id'), 'github_deployments', ['repository_id'], unique=False)

    op.create_table('github_pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('is_merged', sa.Boolean(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=False),
    sa.Column('merge_commit_sha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_pull_requests_pr_number'), 'github_pull_requests', ['pr_number'], unique=False)
    op.create_index(op.f('ix_github_pull_requests_repository_id'), 'github_pull_requests', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_pull_requests')
    op.drop_table('github_deployments')
    op.drop_table('github_commits')
    op.drop_table('github_repositories')
    # ### end Alembic commands ###
