"""create_detection_engine_models

Revision ID: 56fd7fdeaf47
Revises: e81dfe6af726
Create Date: 2026-07-18 21:31:29.900098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56fd7fdeaf47'
down_revision: Union[str, None] = 'e81dfe6af726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_memories_incident_id'), table_name='incident_memories')
    op.drop_index(op.f('ix_incident_memories_organization_id'), table_name='incident_memories')
    op.drop_index(op.f('ix_incident_memories_severity'), table_name='incident_memories')
    op.drop_index(op.f('ix_incident_memories_workspace_id'), table_name='incident_memories')
    op.drop_table('incident_memories')
    op.drop_index(op.f('ix_investigations_incident_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telemetry_events_name'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_project_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_timestamp'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_workspace_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_api_keys_secret_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_telemetry_deployments_environment'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_project_id'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_timestamp'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_version'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_workspace_id'), table_name='telemetry_deployments')
    op.drop_table('telemetry_deployments')
    op.drop_index(op.f('ix_projects_api_key'), table_name='projects')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_remediations_incident_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_workspace_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_telemetry_heartbeats_environment'), table_name='telemetry_heartbeats')
    op.drop_index(op.f('ix_telemetry_heartbeats_project_id'), table_name='telemetry_heartbeats')
    op.drop_index(op.f('ix_telemetry_heartbeats_timestamp'), table_name='telemetry_heartbeats')
    op.drop_index(op.f('ix_telemetry_heartbeats_workspace_id'), table_name='telemetry_heartbeats')
    op.drop_table('telemetry_heartbeats')
    op.drop_table('api_key_permissions')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_member_activities_action'), table_name='member_activities')
    op.drop_index(op.f('ix_member_activities_organization_id'), table_name='member_activities')
    op.drop_table('member_activities')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('api_key_usages')
    op.drop_table('workspace_integrations')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('api_key_audits')
    op.drop_index(op.f('ix_simulation_runs_incident_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_workspace_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_telemetry_metrics_name'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_project_id'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_timestamp'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_workspace_id'), table_name='telemetry_metrics')
    op.drop_table('telemetry_metrics')
    op.drop_table('integration_webhooks')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_incident_embeddings_memory_id'), table_name='incident_embeddings')
    op.drop_table('incident_embeddings')
    op.drop_index(op.f('ix_telemetry_logs_level'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_project_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_timestamp'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_workspace_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_telemetry_exceptions_project_id'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_timestamp'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_type'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_workspace_id'), table_name='telemetry_exceptions')
    op.drop_table('telemetry_exceptions')
    op.drop_index(op.f('ix_integration_providers_key'), table_name='integration_providers')
    op.drop_table('integration_providers')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_status'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_telemetry_health_project_id'), table_name='telemetry_health')
    op.drop_index(op.f('ix_telemetry_health_service_name'), table_name='telemetry_health')
    op.drop_index(op.f('ix_telemetry_health_timestamp'), table_name='telemetry_health')
    op.drop_index(op.f('ix_telemetry_health_workspace_id'), table_name='telemetry_health')
    op.drop_table('telemetry_health')
    op.drop_table('integration_syncs')
    op.drop_index(op.f('ix_incident_tags_memory_id'), table_name='incident_tags')
    op.drop_index(op.f('ix_incident_tags_name'), table_name='incident_tags')
    op.drop_index(op.f('ix_incident_tags_value'), table_name='incident_tags')
    op.drop_table('incident_tags')
    op.drop_table('integration_audits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_audits',
    sa.Column('workspace_integration_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('performed_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('integration_audits_performed_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('integration_audits_workspace_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_integration_id'], ['workspace_integrations.id'], name=op.f('integration_audits_workspace_integration_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_audits_pkey'))
    )
    op.create_table('incident_tags',
    sa.Column('memory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['incident_memories.id'], name=op.f('incident_tags_memory_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_tags_pkey'))
    )
    op.create_index(op.f('ix_incident_tags_value'), 'incident_tags', ['value'], unique=False)
    op.create_index(op.f('ix_incident_tags_name'), 'incident_tags', ['name'], unique=False)
    op.create_index(op.f('ix_incident_tags_memory_id'), 'incident_tags', ['memory_id'], unique=False)
    op.create_table('integration_syncs',
    sa.Column('workspace_integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('imported_resources', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('warnings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_integration_id'], ['workspace_integrations.id'], name=op.f('integration_syncs_workspace_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_syncs_pkey'))
    )
    op.create_table('telemetry_health',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('telemetry_health_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('telemetry_health_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_health_pkey'))
    )
    op.create_index(op.f('ix_telemetry_health_workspace_id'), 'telemetry_health', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_health_timestamp'), 'telemetry_health', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_health_service_name'), 'telemetry_health', ['service_name'], unique=False)
    op.create_index(op.f('ix_telemetry_health_project_id'), 'telemetry_health', ['project_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('organization_members_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('organization_members_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('organization_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_members_pkey')),
    sa.UniqueConstraint('user_id', 'organization_id', name=op.f('uq_organization_member_user_org'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_organization_members_status'), 'organization_members', ['status'], unique=False)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_table('integration_providers',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('overview', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_oauth_supported', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('default_sync_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_providers_pkey'))
    )
    op.create_index(op.f('ix_integration_providers_key'), 'integration_providers', ['key'], unique=True)
    op.create_table('telemetry_exceptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('telemetry_exceptions_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('telemetry_exceptions_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_exceptions_pkey'))
    )
    op.create_index(op.f('ix_telemetry_exceptions_workspace_id'), 'telemetry_exceptions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_type'), 'telemetry_exceptions', ['type'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_timestamp'), 'telemetry_exceptions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_project_id'), 'telemetry_exceptions', ['project_id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('telemetry_logs_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('telemetry_logs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_logs_pkey'))
    )
    op.create_index(op.f('ix_telemetry_logs_workspace_id'), 'telemetry_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_timestamp'), 'telemetry_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_project_id'), 'telemetry_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_level'), 'telemetry_logs', ['level'], unique=False)
    op.create_table('incident_embeddings',
    sa.Column('memory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['incident_memories.id'], name=op.f('incident_embeddings_memory_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_embeddings_pkey'))
    )
    op.create_index(op.f('ix_incident_embeddings_memory_id'), 'incident_embeddings', ['memory_id'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('workspace_members',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workspace_members_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_members_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_members_pkey')),
    sa.UniqueConstraint('user_id', 'workspace_id', name=op.f('uq_workspace_member_user_ws'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_table('integration_webhooks',
    sa.Column('workspace_integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('retry_strategy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('delivery_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delivery_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_integration_id'], ['workspace_integrations.id'], name=op.f('integration_webhooks_workspace_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_webhooks_pkey'))
    )
    op.create_table('telemetry_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('telemetry_metrics_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('telemetry_metrics_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_metrics_pkey'))
    )
    op.create_index(op.f('ix_telemetry_metrics_workspace_id'), 'telemetry_metrics', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_timestamp'), 'telemetry_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_project_id'), 'telemetry_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_name'), 'telemetry_metrics', ['name'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scenario_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('simulation_runs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('simulation_runs_pkey'))
    )
    op.create_index(op.f('ix_simulation_runs_workspace_id'), 'simulation_runs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_incident_id'), 'simulation_runs', ['incident_id'], unique=False)
    op.create_table('api_key_audits',
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('performed_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('api_key_audits_api_key_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('api_key_audits_performed_by_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_key_audits_pkey'))
    )
    op.create_table('workspaces',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('environment', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('ai_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('incident_retention_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('workspaces_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspaces_pkey')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_workspace_org_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.create_table('workspace_integrations',
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_providers.id'], name=op.f('workspace_integrations_provider_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_integrations_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_integrations_pkey'))
    )
    op.create_table('api_key_usages',
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('api_key_usages_api_key_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_key_usages_pkey'))
    )
    op.create_table('invitations',
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('workspaces', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('invitations_invited_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('invitations_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitations_pkey'))
    )
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_table('member_activities',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('member_activities_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('member_activities_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('member_activities_pkey'))
    )
    op.create_index(op.f('ix_member_activities_organization_id'), 'member_activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_member_activities_action'), 'member_activities', ['action'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('workspace_integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credential_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_integration_id'], ['workspace_integrations.id'], name=op.f('integration_credentials_workspace_integration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_credentials_pkey'))
    )
    op.create_table('api_key_permissions',
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('api_key_permissions_api_key_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_key_permissions_pkey'))
    )
    op.create_table('telemetry_heartbeats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('environment', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cpu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('health', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('telemetry_heartbeats_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('telemetry_heartbeats_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_heartbeats_pkey'))
    )
    op.create_index(op.f('ix_telemetry_heartbeats_workspace_id'), 'telemetry_heartbeats', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeats_timestamp'), 'telemetry_heartbeats', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeats_project_id'), 'telemetry_heartbeats', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeats_environment'), 'telemetry_heartbeats', ['environment'], unique=False)
    op.create_table('remediations',
    sa.Column('incident_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fix_strategy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('code_patch', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('github_pr_draft', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rollback_plan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risk_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('runbook', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('remediations_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('remediations_pkey'))
    )
    op.create_index(op.f('ix_remediations_workspace_id'), 'remediations', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_remediations_incident_id'), 'remediations', ['incident_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('organizations_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('environment', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('framework', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('projects_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_projects_api_key'), 'projects', ['api_key'], unique=True)
    op.create_table('telemetry_deployments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('environment', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('telemetry_deployments_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('telemetry_deployments_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_deployments_pkey'))
    )
    op.create_index(op.f('ix_telemetry_deployments_workspace_id'), 'telemetry_deployments', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_version'), 'telemetry_deployments', ['version'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_timestamp'), 'telemetry_deployments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_project_id'), 'telemetry_deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_environment'), 'telemetry_deployments', ['environment'], unique=False)
    op.create_table('api_keys',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('prefix', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('secret_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('environment', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('api_keys_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('api_keys_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey'))
    )
    op.create_index(op.f('ix_api_keys_secret_hash'), 'api_keys', ['secret_hash'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_pkey'))
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('telemetry_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('telemetry_events_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('telemetry_events_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_events_pkey'))
    )
    op.create_index(op.f('ix_telemetry_events_workspace_id'), 'telemetry_events', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_timestamp'), 'telemetry_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_events_project_id'), 'telemetry_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_name'), 'telemetry_events', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('investigations',
    sa.Column('incident_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_outputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('incident_report', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('investigations_pkey'))
    )
    op.create_index(op.f('ix_investigations_incident_id'), 'investigations', ['incident_id'], unique=False)
    op.create_table('incident_memories',
    sa.Column('incident_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('time_taken_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('root_cause', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('recommended_fix', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generated_report', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timeline', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('logs_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metrics_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('deployment_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('incident_memories_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('incident_memories_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_memories_pkey'))
    )
    op.create_index(op.f('ix_incident_memories_workspace_id'), 'incident_memories', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_incident_memories_severity'), 'incident_memories', ['severity'], unique=False)
    op.create_index(op.f('ix_incident_memories_organization_id'), 'incident_memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incident_memories_incident_id'), 'incident_memories', ['incident_id'], unique=False)
    # ### end Alembic commands ###
