"""split_telemetry_tables

Revision ID: e81dfe6af726
Revises: observability_platform
Create Date: 2026-07-18 18:58:36.450042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e81dfe6af726'
down_revision: Union[str, None] = 'observability_platform'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_deployments_environment'), 'telemetry_deployments', ['environment'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_project_id'), 'telemetry_deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_timestamp'), 'telemetry_deployments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_version'), 'telemetry_deployments', ['version'], unique=False)
    op.create_index(op.f('ix_telemetry_deployments_workspace_id'), 'telemetry_deployments', ['workspace_id'], unique=False)
    op.create_table('telemetry_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('stack_trace', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_exceptions_project_id'), 'telemetry_exceptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_timestamp'), 'telemetry_exceptions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_type'), 'telemetry_exceptions', ['type'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_workspace_id'), 'telemetry_exceptions', ['workspace_id'], unique=False)
    op.create_table('telemetry_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_health_project_id'), 'telemetry_health', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_health_service_name'), 'telemetry_health', ['service_name'], unique=False)
    op.create_index(op.f('ix_telemetry_health_timestamp'), 'telemetry_health', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_health_workspace_id'), 'telemetry_health', ['workspace_id'], unique=False)
    op.create_table('telemetry_heartbeats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('memory', sa.Float(), nullable=True),
    sa.Column('health', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_heartbeats_environment'), 'telemetry_heartbeats', ['environment'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeats_project_id'), 'telemetry_heartbeats', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeats_timestamp'), 'telemetry_heartbeats', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeats_workspace_id'), 'telemetry_heartbeats', ['workspace_id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_level'), 'telemetry_logs', ['level'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_project_id'), 'telemetry_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_timestamp'), 'telemetry_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_workspace_id'), 'telemetry_logs', ['workspace_id'], unique=False)
    op.create_table('telemetry_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_metrics_name'), 'telemetry_metrics', ['name'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_project_id'), 'telemetry_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_timestamp'), 'telemetry_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_workspace_id'), 'telemetry_metrics', ['workspace_id'], unique=False)
    op.add_column('telemetry_events', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_telemetry_events_event_type'), table_name='telemetry_events')
    op.create_index(op.f('ix_telemetry_events_name'), 'telemetry_events', ['name'], unique=False)
    op.drop_column('telemetry_events', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_events', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_telemetry_events_name'), table_name='telemetry_events')
    op.create_index(op.f('ix_telemetry_events_event_type'), 'telemetry_events', ['event_type'], unique=False)
    op.drop_column('telemetry_events', 'name')
    op.drop_index(op.f('ix_telemetry_metrics_workspace_id'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_timestamp'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_project_id'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_name'), table_name='telemetry_metrics')
    op.drop_table('telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_logs_workspace_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_timestamp'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_project_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_level'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_telemetry_heartbeats_workspace_id'), table_name='telemetry_heartbeats')
    op.drop_index(op.f('ix_telemetry_heartbeats_timestamp'), table_name='telemetry_heartbeats')
    op.drop_index(op.f('ix_telemetry_heartbeats_project_id'), table_name='telemetry_heartbeats')
    op.drop_index(op.f('ix_telemetry_heartbeats_environment'), table_name='telemetry_heartbeats')
    op.drop_table('telemetry_heartbeats')
    op.drop_index(op.f('ix_telemetry_health_workspace_id'), table_name='telemetry_health')
    op.drop_index(op.f('ix_telemetry_health_timestamp'), table_name='telemetry_health')
    op.drop_index(op.f('ix_telemetry_health_service_name'), table_name='telemetry_health')
    op.drop_index(op.f('ix_telemetry_health_project_id'), table_name='telemetry_health')
    op.drop_table('telemetry_health')
    op.drop_index(op.f('ix_telemetry_exceptions_workspace_id'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_type'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_timestamp'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_project_id'), table_name='telemetry_exceptions')
    op.drop_table('telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_deployments_workspace_id'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_version'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_timestamp'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_project_id'), table_name='telemetry_deployments')
    op.drop_index(op.f('ix_telemetry_deployments_environment'), table_name='telemetry_deployments')
    op.drop_table('telemetry_deployments')
    # ### end Alembic commands ###
