import uuid
from typing import Any, Dict, List, Optional
from datetime import datetime
from sqlalchemy import String, JSON, Boolean, Float, DateTime, ForeignKey, Table, Column, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from sentinel_api.database.base import BaseModel


class DetectionRule(BaseModel):
    """Configurable rules for the anomaly detection engine."""
    __tablename__ = "detection_rules"

    project_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True, nullable=False)
    workspace_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("workspaces.id", ondelete="CASCADE"), index=True, nullable=False)
    name: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    
    # Rule engine configuration
    condition_type: Mapped[str] = mapped_column(String, nullable=False, default="static_threshold") # static_threshold, rolling_window, anomaly
    target_metric: Mapped[str] = mapped_column(String, nullable=False) # e.g., 'http_500_rate', 'cpu_usage', 'latency'
    operator: Mapped[str] = mapped_column(String, nullable=False) # '>', '<', '>=', '<=', '==', '!=', 'anomaly'
    threshold: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    time_window_mins: Mapped[int] = mapped_column(default=5, nullable=False)
    
    severity: Mapped[str] = mapped_column(String, default="Medium", nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # For dynamic ML-based anomalies or multi-condition JSON
    config_json: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)


class Incident(BaseModel):
    """Core Incident tracking generated by the detection engine."""
    __tablename__ = "incidents"

    project_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True, nullable=False)
    workspace_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("workspaces.id", ondelete="CASCADE"), index=True, nullable=False)
    
    # E.g. INC-20260718-1234
    incident_key: Mapped[str] = mapped_column(String, unique=True, index=True, nullable=False)
    
    status: Mapped[str] = mapped_column(String, nullable=False, default="Open") # Open, Investigating, AI Processing, Remediating, Resolved, Closed
    severity: Mapped[str] = mapped_column(String, nullable=False, default="Medium") # Info, Low, Medium, High, Critical
    title: Mapped[str] = mapped_column(String, nullable=False)
    summary: Mapped[Optional[str]] = mapped_column(String, nullable=True)

    # Correlation data
    fingerprint: Mapped[str] = mapped_column(String, index=True, nullable=False) # Used for deduplication within time window
    trigger_rule_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("detection_rules.id", ondelete="SET NULL"), nullable=True)
    
    # Relationships
    timeline: Mapped[List["IncidentTimeline"]] = relationship("IncidentTimeline", back_populates="incident", cascade="all, delete-orphan")
    evidence: Mapped[List["IncidentEvidence"]] = relationship("IncidentEvidence", back_populates="incident", cascade="all, delete-orphan")
    affected_services: Mapped[List["AffectedService"]] = relationship("AffectedService", back_populates="incident", cascade="all, delete-orphan")

    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)


class IncidentTimeline(BaseModel):
    """History of status or severity changes for an incident."""
    __tablename__ = "incident_timeline"

    incident_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("incidents.id", ondelete="CASCADE"), index=True, nullable=False)
    
    action: Mapped[str] = mapped_column(String, nullable=False) # status_change, severity_change, note_added, ai_action
    previous_value: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    new_value: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    metadata_json: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)

    incident: Mapped["Incident"] = relationship("Incident", back_populates="timeline")


class IncidentEvidence(BaseModel):
    """Raw telemetry and correlations that resulted in this incident."""
    __tablename__ = "incident_evidence"

    incident_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("incidents.id", ondelete="CASCADE"), index=True, nullable=False)
    
    evidence_type: Mapped[str] = mapped_column(String, nullable=False) # Log, Metric, Exception, Heartbeat
    source_event_id: Mapped[Optional[str]] = mapped_column(String, nullable=True) # UUID of the raw telemetry event
    payload: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
    
    incident: Mapped["Incident"] = relationship("Incident", back_populates="evidence")


class AffectedService(BaseModel):
    """Services and environments associated with the incident."""
    __tablename__ = "incident_affected_services"

    incident_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("incidents.id", ondelete="CASCADE"), index=True, nullable=False)
    
    service_name: Mapped[str] = mapped_column(String, nullable=False)
    environment: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    deployment_version: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    
    incident: Mapped["Incident"] = relationship("Incident", back_populates="affected_services")


class DetectionHistory(BaseModel):
    """Audit log of detection engine executions (can be truncated periodically)."""
    __tablename__ = "detection_history"

    project_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True, nullable=False)
    rule_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("detection_rules.id", ondelete="SET NULL"), nullable=True)
    
    metric_value: Mapped[float] = mapped_column(Float, nullable=False)
    is_anomaly: Mapped[bool] = mapped_column(Boolean, nullable=False)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    metadata_json: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
