apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel-ai.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "sentinel-ai.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sentinel-ai.name" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sentinel-ai.name" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/api:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health/liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SENTINEL_APP_ENV
              value: {{ .Values.env.SENTINEL_APP_ENV | quote }}
          {{- if .Values.env.envFromSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.env.envFromSecretName }}
          {{- end }}
