from typing import Any, Dict, List
from pydantic import BaseModel, Field


class EvidenceSource(BaseModel):
    """Details of an upstream agent source that provided incident evidence."""

    agent_name: str = Field(..., description="Name of the sub-agent")
    confidence: float = Field(..., description="Agent confidence score")
    findings_count: int = Field(..., description="Number of findings/events parsed")
    critical_issues: List[str] = Field(
        default_factory=list, description="List of high severity issues reported"
    )


class RootCauseHypothesis(BaseModel):
    """An incident cause hypothesis generated by the reasoning engine."""

    id: str = Field(..., description="Hypothesis identifier")
    root_cause_type: str = Field(..., description="Type: e.g. BAD_DEPLOYMENT, DB_OVERLOAD")
    title: str = Field(..., description="Display title of the hypothesis")
    description: str = Field(..., description="Text details of the incident scenario")
    confidence: float = Field(..., description="Confidence rating of this hypothesis")
    supporting_evidence: List[str] = Field(
        default_factory=list, description="Descriptions of supporting observations"
    )
    score: float = Field(..., description="Aggregated ranking score [0.0 - 1.0]")
    timeline_consistency: float = Field(
        ..., description="Chronological consistency ratio [0.0 - 1.0]"
    )


class RootCauseSummary(BaseModel):
    """Comprehensive textual summaries of the root cause findings."""

    executive_explanation: str = Field(..., description="Executive narrative summary")
    technical_explanation: str = Field(..., description="Detailed technical cause explanation")
    evidence_summary: str = Field(..., description="Highlights of the gathered evidence")
    reasoning_summary: str = Field(..., description="Outline of the logical correlation steps")
    alternative_explanations: List[str] = Field(
        default_factory=list, description="Summary of secondary hypotheses"
    )


class RootCauseAgentOutput(BaseModel):
    """The final structured payload output returned by the Root Cause Agent."""

    agent_name: str = Field(..., description="Name of this agent")
    execution_time_ms: float = Field(..., description="Execution elapsed time")
    status: str = Field(..., description="Run outcome")
    confidence: float = Field(..., description="Overall reasoning confidence score")
    root_cause: str = Field(..., description="Main diagnosed root cause")
    supporting_evidence: List[str] = Field(
        default_factory=list, description="Observations directly supporting the root cause"
    )
    alternative_hypotheses: List[RootCauseHypothesis] = Field(
        default_factory=list, description="Secondary options ranked by likelihood"
    )
    reasoning: str = Field(..., description="Logical step-by-step description")
    timeline_summary: List[str] = Field(
        default_factory=list, description="Chronological events leading to the incident"
    )
    evidence_sources: List[str] = Field(
        default_factory=list, description="Sub-agents that provided evidence"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Metadata summary metrics"
    )
